### ISSUE TITLE
Breaking change in base class.

### ISSUE THREAD

**Issue by exiled78** [boro2g/AlexaCore#3]
@boro2g I don't think this example is valid anymore. There is no ctor in the base class that accepts params.

https://github.com/boro2g/AlexaCore/blame/master/README.md#L29

**Comment by boro2g** [comment]
This is now updated to remove the invalid ctor code. 
Thanks for pointing it out.

**Comment by exiled78** [comment]
@boro2g no worries. Thanks for sharing your work.
